### PR TITLE
Fix links to codelabs in internal README files

### PR DESCRIPTION
**Pull request by nico-gonzalez**
Links to the codelabs in the internal README for each of the samples were pointing to the wrong place resulting in a 404 error.

### CODE REVIEW

**Comment by nickbutcher** [comment]
Should we point at the d.android.com versions instead?

**Comment by nico-gonzalez** [comment]
> Should we point at the d.android.com versions instead?

@nickbutcher I used the same links from the outer [README](https://github.com/googlecodelabs/android-compose-codelabs/blob/main/README.md) which are pointing to the right place. I can change them if you have new/different links to point to

**Comment by nickbutcher** [comment]
Sorry, that question was intended for @JoseAlcerreca !

**Comment by JoseAlcerreca** [comment]
Yup, let's point them to the final destination. We just migrated all Android codelabs to d.android.com so we have redirects from
https://codelabs.developers.google.com/codelabs/jetpack-compose-theming
to
https://developer.android.com/codelabs/jetpack-compose-theming

Feel free to include the main README in this PR or we'll do it separately. 

Thanks!

**Comment by JoseAlcerreca** [comment]
Hey Nico, can you use the final destination? developer instead of d. Thanks!

**Comment by nico-gonzalez** [comment]
> Hey Nico, can you use the final destination? developer instead of d. Thanks!

done @JoseAlcerreca !

**Comment by nico-gonzalez** [comment]
@yrezgui why is this closed? Links are still failing on main branch

**Comment by yrezgui** [comment]
@nico-gonzalez My bad, after I merged the alpha08 changes, it deleted the branch, which closed automatically your PR.
Can you re-open it and target main, I'll merge straightaway

**Pull request closed without merging**
