### PR TITLE
Fix the name of the argument of TodoScreen

### PR DESCRIPTION
**Pull request by thagikura**
to match the instructions in https://developer.android.com/codelabs/jetpack-compose-state#3

Otherwise the instructed code doesn't compile because the name of the argument doesn't match with the actual name.

### CODE REVIEW

**Comment by thagikura** [comment]
Note that finished directory has the fixed code already.

https://github.com/googlecodelabs/android-compose-codelabs/blob/main/StateCodelab/finished/src/main/java/com/codelabs/state/todo/TodoScreen.kt#L68

**Comment by thagikura** [comment]
Friendly ping @florina-muntenescu

**Comment by florina-muntenescu** [comment]
Hey @thagikura, not sure why this still looks like it needs changes. 
I made these changes as part of beta01 update:
https://github.com/googlecodelabs/android-compose-codelabs/blob/main/StateCodelab/start/src/main/java/com/codelabs/state/todo/TodoScreen.kt#L49

Thank you for creating this PR!

**Comment by thagikura** [comment]
The code snippet in the instruction says the name of the arguments as follows. So the argument itemsList (before the fix) doesn't exist.
So using the code snippet didn't compile. 

```
@Composable
private fun TodoActivityScreen(todoViewModel: TodoViewModel) {
   val items = listOf<TodoItem>() // in the next steps we'll complete this
   TodoScreen(
       items = items,
       onAddItem = { }, // in the next steps we'll complete this
       onRemoveItem = { } // in the next steps we'll complete this
   )
}
```

But thanks for the fix!

**Pull request closed without merging**
